### ISSUE TITLE
initial setup

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/toy-library#1]
### TODO:
- [ ] add ping handler
- [ ] add handler test
- [ ] add database migration tool
- [ ] add config management tool
- [ ] add basic model
